apiVersion: v1
kind: Secret
metadata:
  name: traduce-senas-secrets
type: Opaque
stringData:
  db-host: "traduce-senas-db"
  db-name: "traduce_senas"
  db-user: "senas_user"
  db-password: "CAMBIAR_EN_PRODUCCION"
  jwt-secret: "CAMBIAR_EN_PRODUCCION"
