apiVersion: v1
kind: Service
metadata:
  name: traduce-senas-backend
  labels:
    app: traduce-senas
    tier: backend
spec:
  selector:
    app: traduce-senas
    tier: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: traduce-senas-frontend
  labels:
    app: traduce-senas
    tier: frontend
spec:
  selector:
    app: traduce-senas
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
